const fs = require('fs');
const path = require('path');
const config = require('./config');
const { generateArticle, generateImage, expandTopics } = require('./content');

const OUTPUT_FILE = path.join(__dirname, '../templates/articles.js');

const run = async () => {
    console.log('🏭 Starting Bulk Content Generation...');

    // 1. Expand Topics
    const seedTopic = config.content.topic;
    const subtopics = config.content.subtopics;

    let allTopics = [];

    // Add seed topic variations
    const expandedSeed = await expandTopics(seedTopic);
    allTopics = [...allTopics, ...expandedSeed];

    // Add subtopics
    for (const sub of subtopics) {
        const expandedSub = await expandTopics(`${seedTopic} ${sub}`);
        allTopics = [...allTopics, ...expandedSub];
    }

    // Limit to ~20 articles for this demo
    allTopics = allTopics.slice(0, 20);
    console.log(`📝 Generated ${allTopics.length} article topics.`);

    // 2. Generate Articles
    const articles = [];
    let idCounter = 1;

    for (const topic of allTopics) {
        console.log(`Processing [${idCounter}/${allTopics.length}]: ${topic}`);

        // Generate Text
        const articleData = await generateArticle(topic);

        // Generate Image
        const imageUrl = await generateImage(topic);

        articles.push({
            id: idCounter++,
            title: articleData.title,
            excerpt: articleData.excerpt,
            content: articleData.content, // New field for full content
            category: articleData.category,
            author: articleData.author,
            date: articleData.date,
            readTime: articleData.readTime,
            image: imageUrl,
            featured: idCounter === 2 // Make the first one featured (id 1 is usually reserved or special)
        });

        // Tiny delay to simulate API latency
        await new Promise(resolve => setTimeout(resolve, 100));
    }

    // 3. Save to articles.js
    const fileContent = `// Auto-generated by Site Factory
const articles = ${JSON.stringify(articles, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`✅ Successfully generated ${articles.length} articles in templates/articles.js`);
};

run();
